repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: Тематическое_моделирование.ipynb
      - id: end-of-file-fixer
        exclude: Тематическое_моделирование.ipynb
      - id: check-yaml
        exclude: Тематическое_моделирование.ipynb
      - id: check-docstring-first
        exclude: Тематическое_моделирование.ipynb
      - id: check-added-large-files
        exclude: Тематическое_моделирование.ipynb
      - id: check-merge-conflict
        exclude: Тематическое_моделирование.ipynb




  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        exclude: Тематическое_моделирование.ipynb
