[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_no_return = True

[mypy-pdfminer.*]
ignore_missing_imports = True

[mypy-pytesseract]
ignore_missing_imports = True

[mypy-pdf2image]
ignore_missing_imports = True

[mypy-easyocr]
ignore_missing_imports = True

[mypy-fitz]
ignore_missing_imports = True

[mypy-cv2]
ignore_missing_imports = True

[mypy-yaml]
ignore_missing_imports = True

[mypy-gensim]
ignore_missing_imports = True

[mypy-gensim.models]
ignore_missing_imports = True

[mypy-gensim.corpora]
ignore_missing_imports = True

[mypy-nltk.*]
ignore_missing_imports = True

[mypy-pandas]
ignore_missing_imports = True

[mypy-pyLDAvis.*]
ignore_missing_imports = True

[mypy-seaborn]
ignore_missing_imports = True

[mypy-pymorphy2]
ignore_missing_imports = True

[mypy-pandas]
ignore_missing_imports = True
warn_return_any = False

[mypy-pyLDAvis.gensim_models]
ignore_missing_imports = True
